[package]
name = "ruster"
version = "0.1.0"
authors = ["Lai0pei <xiaopeiymo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
diesel = "1.4.5"